language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:giskou/librocksdb'
    packages:
    - gcc
    - g++
    - libssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - libsnappy-dev
    - librocksdb
    - libsnappy-dev

rust:
- stable

cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.local"
  - "$TRAVIS_BUILD_DIR/target"
sudo: false

env:
  global:
  - CLIPPY_VERS=0.0.175
  - RUSTFMT_VERS=0.9.0
  - SODIUM_VERS=1.0.13
  - ROCKSDB_VERS=5.6.1
  - DEADLINKS_VERS=0.3.0
  - RUSTFLAGS="-C link-dead-code"
  - RUST_LOG=off
  - ROCKSDB_LIB_DIR=/usr/lib/x86_64-linux-gnu
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu

install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz
    tar xvf libsodium-$SODIUM_VERS.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make -j $(nproc)
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
- |
  if [[ "$FEATURE" == "clippy" ]]; then
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  fi
- |
  if [[ "$FEATURE" == "non-fatal-checks" ]]; then
    cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
  fi
- |
  if [[ "$FEATURE" == "fmt" ]]; then
    cargo-audit -V || cargo install cargo-audit --force
    rustfmt -V | grep $RUSTFMT_VERS || cargo install rustfmt --vers $RUSTFMT_VERS --force
  fi
- cargo install --list
- cd $TRAVIS_BUILD_DIR
- cargo update

script: skip

jobs:
  include:
  - stage: test
    env:
    - FEATURE=non-fatal-checks
    script:
    - cargo doc --no-deps && cargo deadlinks --dir target/doc || true
  - stage: test
    env:
    - FEATURE=fmt
    script:
    - cargo audit
    - cargo fmt -- --write-mode=diff
  - stage: test
    rust: nightly-2017-12-11
    env:
    - FEATURE=clippy
    script:
    - cargo clippy -- -D warnings
  - stage: test
    script:
    - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        cargo test;
      fi
    - |
      if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        cargo test --features rpc_tests;
      fi
notifications:
  slack:
    secure: YHS1dJE+g28M3iW9MG2ShgVd20nHbFLd5i7TbID59RnYl/SAKlGUeTtUTjK0VpnzaTX1ETLSXGcjj7Xx1sI7I/4f1obyMWMEUg7k+JfnkYOcYCiHCymt3L/QK1n8HNbprkrEx8VDO79BzTtB9az0DhQDpf18hJ8VYr3PNxkGgENJNIMf8y1r5/qrp6Tww+/Nw60I1dhdSQCvvZStbQCW47f2pHHcASnUvEpy9CSYjnfgUappMZkZVuYlY8vaV0yB8OrKZSV2nrJwGaoNXkbkYJtCcd4/ZSSGM+hz2dGjmvinjAOpyrUO+TzOHoKBad1/3VRj9ZX5L5CTBfkaeoLEJibdmRu/+0KvtFQFrqskap4CpnKjEh8aeAuYZEWhPy52IQehRF0kyo5ZPwe0pvFZM3KdaMEOT03Pnkqb/UxmsWa/91hC/EIRhWXKk4Y0UWtwhrdnbyKPquasBgZR+0Prh41s966S3MxohsVYPC23jk3vHOZFmNpmoEQsMh5FZgoQUNesVarv8tmQBS5t3kYXRDmrH9J8aLts0ovDT+i1ovmjnog9VOfsEmk8FBlTdkTxtt/x5n0Zf8oEhrgvMp5rB2JvhvxG1iT+GBcJia57yuuOaC0ermGtQqEvSpkQon2IPUtbusaUlt1jEXe3fR91Y11S3PZdX3nuAFnGHyE1pyc=
    rooms:
      secure: U7ZFHx1O0FPl2IeYHjxaQ7RrceDSPIirBVKv5IEmlQeXMQ1+MJspyKJ1HUZDrbbqDWfuqIOVDbht5Bqa6D0NOXgpMEf7VsweAkBJj0rocWNZkpf0D0WBENxgA/VNI5lGRlglh2TS+5Q3Rvsg7DikFLDZa97rLKnf0LxwJTq8YT1ZkpEA7J7jQ21qCcygnFzm9gFk+Md2/gNpCAou3x+RdhkHGj4lv6wsr4MAn6l5YP3eiwgHhtkV0C/iorltlKoy7WLHun8uRCOcfDPCN0ugw37r4ZoStwdtXMI6U8CSFUaHUVRkp+MT9FXzOxF7e4FvxuHezrjLpR+CcAyvd1ZCNOwGZiGnF+YGFGeJ0D6PcP9rIDde1LcAbaSjYHsVagj/VX76IJX3P/k5JHRGlWMpPf8BW9ZWsozQZdKrRGIw9DFTaz4UWUPxwIfIpm3qSVwYM18T0SoTfHSw7Osg5MHmxs34D5SelTpJYvDH0pSsplFqbvgrSpl8y++4jBr1dWyJ8XKwdyk0CYIYf4kf7yoGbTmFlsc0wqHi3wrTWGIgSeQYHGmnTIZSveypMcT3OlaVljlC5OAfolhbwJMXWr0cpwTrpcNLSDkzx3kfzk0O+Df6s7ilJb4ilTN+r/zl7PJCGPQVU1+MqquZizHWJetPniV1Fms2106Tael1klSUd7w=
