[package]
name = "exonum-btc-anchoring"
version = "0.3.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
exonum = "0.3.0"
exonum_bitcoinrpc = "0.1.1"

bitcoin="0.10.0"
secp256k1 = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.0.0"
log = "0.3.0"
clap = "2.22.1"
rand = "0.3.0"
derive-error = "0.0.4"
router = "0.5.1"
iron = "0.5.1"
mount = "0.3.0"
toml = "0.4.0"
tempdir = "0.3.5"

[dev-dependencies]
exonum-configuration = "0.3.0"

[patch.crates-io]
exonum = { git = "https://github.com/exonum/exonum", rev = "391d0a14bd84e040bf2edc737578fff2ea2e2265" }

[patch.crates-io.exonum-configuration]
git = "https://github.com/exonum/exonum-configuration"
rev = "9e18e38978edbd548f573f76ba62edd78b465dc3" 

[features]
default = []
sandbox_tests = []
rpc_tests = []
