[package]
name = "exonum-btc-anchoring"
version = "0.8.1"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/bitcoin-anchoring/"
repository = "https://github.com/exonum/exonum-btc-anchoring"
documentation = "https://docs.rs/exonum-btc-anchoring"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "bitcoin", "anchoring"]
categories = ["database-implementations"]
description = "An Exonum service that provides anchoring to Bitcoin blockchain."

[badges]
travis-ci = { repository = "exonum/exonum-btc-anchoring" }

[dependencies]
# We'll have to use concrete revision until 0.9 is released.
# exonum = "0.9.0" 
exonum = { git = "https://github.com/exonum/exonum", rev = "0da10adb4511818c3927da32808c3cb20d8b52b8" }
exonum_bitcoinrpc = "0.5.1"

bitcoin = "=0.13.1"
byteorder = "1.0.0"
btc-transaction-utils = "0.2.0"
clap = "2.22.1"
display_derive = "0.0.0"
failure = "0.1.1"
failure_derive = "0.1.1"
log = "0.4.0"
rand = "0.4.2"
secp256k1 = "0.9.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
tempdir = "0.3.5"
toml = "0.4.0"

[dev-dependencies]
# exonum-configuration = "0.9.0"
# exonum-testkit = "0.9.0"
exonum-testkit = { git = "https://github.com/exonum/exonum", rev = "0da10adb4511818c3927da32808c3cb20d8b52b8" }
exonum-configuration = { git = "https://github.com/exonum/exonum", rev = "0da10adb4511818c3927da32808c3cb20d8b52b8" }
libc = "0.2.21"
pretty_assertions = "0.5.1"

[features]
default = []
rpc_tests = []
