[package]
name = "exonum_bitcoinrpc"
version = "0.1.0"
authors = ["Exonum Team <exonum@bitfury.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.3"
bitcoin = "0.9.0"
hex = "0.2"
env_logger = "0.3"

[dependencies.exonum-jsonrpc-v1]
version="0.2"
path="../jsonrpc-v1"